### ISSUE TITLE
Garcia-Gordon interpretaion

### ISSUE THREAD

**Issue by aappling-usgs** [GLEON/LakeMetabolizer#100]
The original paper by Garcia & Gordon (1992) gives coefficients for use with this Eq. 8, in which T^2 appears twice (first multiplied by A2, then by A3):

```
lnC* = A0 + A1 T + A2 T^2 + A3 T^2
+ A3 T^3 + A4 T^4 + A5 T^5
+ S(B0 + B1 T + B2 T^2 + B3 T^3)
+ C0 S^2                        (8)
```

However, (1) this is an odd way to parameterize a function, and (2) interpretations I've seen treat this as a typo and omit the A3 T^2 term (http://web.uvic.ca/~rhamme/O2sol.m, https://water.usgs.gov/admin/memo/QW/qw11.03.pdf). Neither of these references is externally peer reviewed, but they are consistent with one another, and the latter is widely used.

These two references also use the fit to Benson and Krause's data (first 2 columns of Table 1) rather than the Combined fit (last 2 columns of Table 1). This is consistent with the final sentence of Garcia & Gordon: "For routine computation of Co* in seawater, we recommend using Eq. 8 and the solubility coefficients in Table 1 derived from the more precise data of Benson and Krause (1984)".

LakeMetabolizer:::o2.at.sat.base with model='garcia' includes the A3 T^2 term and uses the combined fit rather than the fit to Benson and Krause's data. The inclusion of A3 T^2 has the larger impact. I'd be very interested in thoughts from @lawinslow, @robohall, or others on these decisions.

**Comment by robohall** [comment]
Hmm,.  I see that I use the “ignore the A3 T^2 term” approach which agrees with Hamme and USGS.  That is the correct thing to do, adding the  A3 T^2,  means that the sat calc is off by 0.4 at high and low temps.  No way we are that far off and I have checked my calcs with tables.  It is a typo.

**Comment by lawinslow** [comment]
Nice find. I wasn't aware of that typo. @aappling-usgs going to do a PR?

**Comment by aappling-usgs** [comment]
Yes I am - coming later this morning
