### ISSUE TITLE
DO.sat conversion from ml/L to mg/L

### ISSUE THREAD

**Issue by aappling-usgs** [GLEON/LakeMetabolizer#101]
DO solubility is computed by Weiss, Garcia-Gordon, etc. in milliliters per liter (ml/L), but we need this value in mg/L. Several coefficients exist in the literature for this conversion.

Staehr et al. 2012 cite Weiss 1970 for a coefficient of `1.423`.

USGS #81.11 memo (http://water.usgs.gov/admin/memo/QW/qw81.11.html) says,
> The DO solubility is calculated in milliliters per liter 
> (ml/L) which must be multiplied by the constant `1.4276` to 
> convert to milligrams per liter (mg/L).

A more recent USGS memo (https://water.usgs.gov/admin/memo/QW/qw11.03.pdf) corrects the previous one, writing,
> The Weiss equations compute a result in units of mL/L, and a factor was
> used to convert that result to mg/L. Unfortunately, the factor used by USGS since 1981 was
> based on an incorrect assumption that the Weiss results were for an ideal gas at standard
> temperature and pressure (STP: 1 atm, 0 °C). In fact, Weiss intended his results to be expressed
> as the volume occupied by oxygen as a real (non-ideal) gas at STP (see Benson and Krause,
> 1980). Therefore, the 1.4276 factor used by USGS in Technical Memorandum 81.11 to convert
> mL/L to mg/L is incorrect; that factor should have been `1.42905` mg/mL. 

Based on this progression of recommendations, I suggest that LakeMetabolizer should adopt `1.42905`. I can include this change in my next pull request.

**Comment by rBatt** [comment]
Nice. We might want to include some of that information in the help pages.
Perhaps simply as a reference, note, detail. Whichever.

**Comment by aappling-usgs** [comment]
Good idea, @rBatt. I will update the roxygen2 block for o2.at.sat with the new citations and a longer description paragraph detailing the the choices made in the code.
