### ISSUE TITLE
Should the initial observation be fit for error.type="OE"? 

### ISSUE THREAD

**Issue by lawinslow** [GLEON/LakeMetabolizer#110]
From Gordon: 
> I hope this isn't too late for your manuscript....but I recently realized I missed something in my review of your paper.  It's with regard to the observation versus process error models and how you initialize the estimated O2.  With an observation error model, you also need to estimate the starting O2 concentration as a free parameter.  I believe you start the model at the first data point, yes? 

We're currently using the first value, but I think he's right, we should be letting the initial observation freely vary as well. 

Thoughts? @rBatt @jzwart @pchanson?

**Comment by jzwart** [comment]
yeah, good point. It's not truly an OE model currently. Easy to fix, and we can set the optim guess to initial DO obs unless DOobs[1] is NA, then use min DOobs or next closest DOobs or something like that.

**Comment by lawinslow** [comment]
We're assuming no NA values right now anyway, so I'll just pull the guess from the initial value. I'm working on this section right now anyway, will have PR in a few min.

**Comment by pchanson** [comment]
Agreed.

**Comment by rBatt** [comment]
Yeah, the first observed value is typically handled as a guess for the
first value of the time series, which can vary.
