### ISSUE TITLE
GPP miscalculation in metab.bookkeep()

### ISSUE THREAD

**Issue by joelwharrison** [GLEON/LakeMetabolizer#137]
GPP is calculated as NEP during the photoperiod minus R for a 24-hour period.  It should be calculated as NEP - R, or as NEP during the photoperiod minus R during the photoperiod.  Example below:

freq <- 24

hr <- 0:23
photoperiod <- c(FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE)
r <- rep(-1, 24)
gpp <- c(0,0,0,0,1,2,3,3.5,4,4.5,5,6,6,5,4.5,4,3.5,3,2,1,0,0,0,0)
nep <- r + gpp

plot(gpp ~ hr, type='l', ylim=c(-3,6), ylab='Metabolism (mg-O2/L)', col=3, lwd=2)
abline(h=0, lty=2, col=8)
lines(r ~ hr, col=4, lwd=2)
lines(nep ~ hr, col=2, lwd=2)
legend('topright', legend=c('GPP','NEP','R'), lty=1, col=c(3,2,4), lwd=2, bty='n')

R <- mean(r[-photoperiod]) * freq
NEP <- mean(nep) * freq

GPP <- sum(nep[photoperiod]) - sum(r[photoperiod])
GPP == NEP - R # check

GPP <- mean(nep[photoperiod]) * sum(photoperiod) - R
GPP == NEP - R # check

metab.bookkeep
R <- mean(nep.night, na.rm = TRUE) * freq
NEP <- mean(delta.do.metab, na.rm = TRUE) * freq
GPP <- mean(nep.day, na.rm = TRUE) * sum(dayI) - R
metab <- data.frame(GPP = GPP, R = R, NEP = NEP)

**Comment by jzwart** [comment]
Hi @joelwharrison, sorry for the slow reply. 
I agree with your statement
>It should be calculated as NEP - R, or as NEP during the photoperiod minus R during the photoperiod. 

I _think_ you might be using an old version of LakeMetabolizer as the code you reference at the bottom of your comment 
```GPP <- mean(nep.day, na.rm = TRUE) * sum(dayI) - R```
was addressed in a pull request [here](https://github.com/GLEON/LakeMetabolizer/pull/121/files). 

You check what version of LakeMetabolizer you're using with `packageVersion("LakeMetabolizer")`. 

I'm also noticing that the out-of-date code might still be on CRAN. I will get the most up-to-date version on CRAN. 

In the meantime, you can get the up-to-date code on the master branch with `devtools::install_github('GLEON/LakeMetabolizer')` .

**Comment by joelwharrison** [comment]
Thank you.  I am using v.1.5.0 which appears to be the most recent on CRAN.  I'll seek out v.1.5.3.
