### ISSUE TITLE
wtr.heat.map error in plot

### ISSUE THREAD

**Issue by RFlazcano** [GLEON/LakeMetabolizer#140]
I have just started going through a tutorial on the package (which I have attached) and I have followed all the steps described but I am getting the following error with my heat map.  Is there details missing in this step-by-step tutorial that is resulting in the error message? 
[buoyData.pdf](https://github.com/GLEON/LakeMetabolizer/files/6072980/buoyData.pdf)

Error in plot.window(xlim, ylim, "", xaxs = xaxs, yaxs = yaxs, asp = asp) : 
  need finite 'xlim' values
In addition: Warning messages:
1: Unknown or uninitialised column: `y`. 
2: Unknown or uninitialised column: `x`. 
3: In min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
4: In max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf

**Comment by hdugan** [comment]
The tutorial was made in 2016, and since then there have been some `tidyverse` package updates that cause errors in old code. Specifically the `wtr.heat.map` function doesn't let you input a tibble. 

Try instead 
`wtr.heat.map(as.data.frame(buoyHourlyWide))`

**Comment by RFlazcano** [comment]
Ok, got it! Thank you!
