### ISSUE TITLE
Error calculating lwnet

### ISSUE THREAD

**Issue by RFlazcano** [GLEON/LakeMetabolizer#143]
I am trying to calculate lwnet but keep encountering this error:  
Error in SatVapor/1000 : non-numeric argument to binary operator

I have been going off the demo so I've defined all the arguments in the calculation as well input my data frame as a complete time-series with all my variables as numeric except for the datetime.

**Comment by hdugan** [comment]
This is hard to troubleshoot. Are the demo examples working for you? 

Can you give an example of your data and error? Something like:

``` r
# install.packages('LakeMetabolizer')
library(LakeMetabolizer)
#> Loading required package: rLakeAnalyzer

## Base example
dateTime <- as.POSIXct("2013-12-30 23:00")
Uz <- 3
airT <- 20
RH <- 90
sw <- 800
wndZ <- 2
Kd <- 2
lat <- 54
lake.area <- 5000 
atm.press <- 1013
Ts <- 22
calc.lw.net.base(dateTime,sw,Ts,lat,atm.press,airT,RH)
#> [1] -52.64892
```

<sup>Created on 2021-10-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hdugan** [comment]
I think part of the problem might just be switching between the column header of `wtr` and `wtr_1`. Also, make sure that you have the latest LakeMetabolizer version installed from GitHub (it has a few updates which might be part of your problem). 

Anyway, this worked for me, so hopefully it works for you:

```
devtools::install_github('GLEON/LakeMetabolizer') # Make sure newest version is installed

library(tidyverse)
library(LakeMetabolizer)
library(lubridate)

data = read_csv('A_QC.csv') %>% 
  rename(wtr = wtr_1) %>% #remove depth from column header
  mutate(datetime = ymd_hms(datetime))
  
corral.area <- 75.5
atm.press <- 961.87
elevation <- 396.72
latitude <- 49.71
longitude <- -93.7766
Kd <- 0.00951
wnd.z = 10

o2.sat <- o2.at.sat(data[c("datetime", "wtr")], baro = atm.press, altitude = elevation, salinity =0.01, model = "garcia-benson")
data <- merge(o2.sat, data)

lwnet <- calc.lw.net(data, latitude, atm.press)
data = merge(data, lwnet)

data = data %>% rename(wtr_1 = wtr) # Add depth to column header 
k600.macintyre <- k.macIntyre(ts.data = data, wnd.z = wnd.z, Kd = Kd, atm.press = atm.press)
```

**Comment by RFlazcano** [comment]
Yes, Thank you! This works now
