### ISSUE TITLE
Wind speed units

### ISSUE THREAD

**Issue by RFlazcano** [GLEON/LakeMetabolizer#145]
I am using the Vachon estimate for gas exchange and I am unsure if my units for wind speed are correct. I am not scaling to U10 because my wind speed data was measured at 10 m. I see that when using wind.scale to scale wind speed that it is unit agnostic but if I am not sclaing to 10 m with wind.scale because my wind speed is already at 10 m is there an issue with my wind speed being in km/hr?

**Comment by jzwart** [comment]
Yes, your wind speed should in units of `m/s` before input to any of the gas exchange functions as they assume the units are `m/s`. If you input in `km/hr` you will get a gas exchange estimate that is biased high, e.g.: 
```
> wind_km_hr = 9
> wind_m_sec = wind_km_hr * 1000 / 3600
> k.vachon.base(wnd = wind_km_hr, lake.area = 10000)
[1] 2.1144
> k.vachon.base(wnd = wind_m_sec, lake.area = 10000)
[1] 1.0224
```

**Comment by RFlazcano** [comment]
Thank you!
