### ISSUE TITLE
option for constraining metab estimates positive

### ISSUE THREAD

**Issue by jzwart** [GLEON/LakeMetabolizer#72]
For example, currently estimates of GPP can be negative, which biologically cannot happen. I suppose one could ignore these results without the option of constraining positive but it might be nice to have everything in the right direction. 

To do so, I think we would just need to exponentiate the gpp and r parameters.

**Comment by lawinslow** [comment]
I'm going to table this for now. The option to constrain estimates across the models is something we could build in. But it will require a champion to do it across the models (much like a non-linear Productivity-Irradiance relationship).
