### ISSUE TITLE
SW to PAR conversion wrong given stated units

### ISSUE THREAD

**Issue by lawinslow** [GLEON/LakeMetabolizer#75]
From Peter:

>The function that you have is 
> sw.to.par.base
```{r} 
function (sw) 
{
    par = sw * 0.473
}
<environment: namespace:LakeMetabolizer>
````
 
> which seemed funny to me. The citation in the help file is to Britton and Dodd 1976, which I looked up. They do give a 47% number for the proportion of shortwave energy in the PAR spectrum, but this number should come after converting the units from umol m-2 s-1 to W m-2. The conversion used for that is given in the first paragraph of the methods section as 4.57 umol m-2 s-1 for clear-sky irradiance, and 4.24 umol m-2 s-1 for diffuse radiation. 
The tables in the paper give values for direct conversions (taking into account unit conversions) under the “Relationship” column, and they fall into the range of 
```{r} 
par = 2.08 * sw
````
>to 
>```{r}
par = 2.61 * sw
````
> with clear-sky summer irradiance days generally in the 2.1-2.2 range.
> Just thought that you’d like to be aware—the value that the function returns for PAR as written should be interpreted as W m-2 units, not umol m-2 s-1. The same problem holds for the reverse conversion (sw.to.par.base).

**Comment by hdugan** [comment]
Wow does that paper toss around units 
`1 W/m2 = 4.57 uE/sec/m2` is equivalent to `1 MJ/m2/day = 4.57 E/m2/day`
where `1 uE = 1 micromole`
So, our function can stay the same, as long as it's clear that both PAR and SW are in W/m2
Any answers need to be multiplied by 4.57 (for clear sky) for units to be in umol/sec/m2

**Comment by lawinslow** [comment]
Yeah, though for convenience, we should change it to accept umol/m^2/day or /sec (forget which) as that's the more common PAR unit. Plus, documentation doesn't say W/m^2 of course.

**Comment by lawinslow** [comment]
From Greg S.:
> I believe 2.047 is a more appropriate conversion factor. I believe this is what is cited in Kalff's limnology textbook.

**Comment by jread-usgs** [comment]
For a sanity check, just regress SW and PAR from NTL lakes.

**Comment by lawinslow** [comment]
Kalf Chapter 10 says 2.11 as the conversion. I'm going to go with that.

**Comment by jread-usgs** [comment]
One last comment - you could have the conversion factor as are arg that defaults to 2.11. I think the conversion is variable in time and space, so you may want to let people have some play with it if it makes sense.

**Comment by lawinslow** [comment]
Good call.

**Comment by lawinslow** [comment]
Oh man, just dug into this, we just had the coefficients switched between par.to.sw and sw.to.par.

**Comment by jread-usgs** [comment]
```R
error('sorry')
```

**Comment by jread-usgs** [comment]
:neckbeard:

**Comment by lawinslow** [comment]
Shouldn't that be 

```R
stop('sorry')
````

**Comment by jread-usgs** [comment]
double the sorry when you can't even error right.

**Comment by lawinslow** [comment]
Here's Britton and Dodd
![image](https://cloud.githubusercontent.com/assets/347600/6249660/4642fc3e-b74e-11e4-8b4e-be7238665d15.png)

@hdugan where did you get the 4.57 number from?

**Comment by hdugan** [comment]
4.57 is a unit conversion... I think.

**Comment by lawinslow** [comment]
Ah, probably doesn't take into account difference in wavelength coverage. thanks.
