### ISSUE TITLE
figure for metab IW paper

### ISSUE THREAD

**Issue by jread-usgs** [GLEON/LakeMetabolizer#82]

**Comment by lawinslow** [comment]
Figure code is here
https://github.com/GLEON/LakeMetabolizer/blob/master/demo/

**Comment by jread-usgs** [comment]
thx, perfect

**Comment by jread-usgs** [comment]
Assuming this is just for: https://github.com/GLEON/LakeMetabolizer/blob/master/demo/fig_k600.R
Let me know if I am wrong

**Comment by jread-usgs** [comment]
I didn't think the noisey-ness of 7 models is worth showing to make this point. I did an hourly running average to show the key differences between the models w/ different forcings.

**Comment by jread-usgs** [comment]
![image](https://cloud.githubusercontent.com/assets/2349007/7325143/da162416-ea81-11e4-8cdc-3eb4af1364d8.png)

@lawinslow @rBatt comments?
please help with colors........

**Comment by rBatt** [comment]
Is this on the master branch? I'm not getting the same plot

**Comment by jread-usgs** [comment]
no, its on my pull request #87

**Comment by rBatt** [comment]
Anyway, here are 7 colors:

cols <- c("#1b9e77", "#d95f02", "#7570b3", "#e7298a", "#66a61e", "#e6ab02",
"#a6761d")

I don't understand the way you did the rest of the formatting, so I
couldn't remake the figure properly (I find it better to set the png units
to "in", define the figure dimensions in the dimensions that'll appear in
the paper, then in par() set ps=8. This make it easier to conform to
journal standards, and avoids figures that look good on your screen but odd
in print (b/c of the mismatch of screen resolution and how it can change
your perception of what an acceptable font size is).

When I tried making those changes, I noticed that other things in the
figure didn't match what you had (ylim=c(0,10)), and that the figure
margins were gigantic (5?!). Your figure looks nice, and the differences I
was seeing was likely just b/c I was messing with the resolution and fonts.

**Comment by rBatt** [comment]
OK i liked it so I merged, i'll pull in new, branch, make my changes and
notify

**Comment by jread-usgs** [comment]
in the future, you can pull down and merge my fork with your local stuff by doing this
`git pull https://github.com/GLEON/LakeMetabolizer.git master`

That way you can review what I did locally and recommend changes for me before the PR comes in.

**Comment by rBatt** [comment]
Are you suggesting I pull in your branch, edit on your branch but locally,
then push my changes to your branch?

**Comment by jread-usgs** [comment]
sorry, didn't know you knew how to do that. I thought you meant you merged my PR, but you didn't.

**Comment by rBatt** [comment]
I did. I didn't know how to do that ;)

**Comment by rBatt** [comment]
I still am a little confused, but I understand that what I did was pretty
roundabout, and that I shouldn't have to merge your PR to make changes on
your branch.

When I do git pull, I don't get the other branches. I didn't try to the
full code – I was just operating w/in my text editor git functionality,
which only has default "git pull"

**Comment by jread-usgs** [comment]
oh, the instructions I gave you were command line, assuming your current directory is your git project

**Comment by jread-usgs** [comment]
@rBatt 's addition:
![image](https://cloud.githubusercontent.com/assets/2349007/7326037/fd68e754-ea87-11e4-888a-73cf0cfcf0de.png)

One key difference here is the clear color contrast between `read` and `soloviev`. The breaker-action makes those two diverge in panel b, but they are almost identical in panel a.

**Comment by rBatt** [comment]
Are the colors OK? See the link I used in the commit. In general, I just go
here: http://colorbrewer2.org/ for colors, then try to make it color blind
friendly (or closest).

My current gripe is that our font sizes are too big.

If you make this figure with the following setup it would get the fonts and
proportions about right, I think:

png(..., width=5, height=3.5, units="in", res=150)
par(mfrow=c(1,2), mar=c(2,1,0.1,0.1), oma=c(0.5, 1,0,0), mgp=c(1.0, 0.2,
0), tcl=0.2, ps=8)

the key thing is that I'm setting the dimensions of the figure to inches
b/c journals say your figures have to be a size and a resolution, so this
makes it explicit that we're adhering to that. While it's still just a
number of pixels, the key is to make sure that the font size is appropriate
– journals also have font size limits. Usually fonts need to be between 6
and 10, and it's typically important to be consistent. I find that for most
journals the width of a column in print is ~3.5 inches; so a square
1-column figure actually looks pretty good w/ 8 pt font, hence the ps = 8
that I have. When viewing a default size figure with 8 point font on your
screen, it'll look terrible. But if you get the sizing and resolution down
to what it should be, 8 pt looks really good.

I've made this mistake before – not keeping your fonts small like this can
result is surprisingly jumbo font when the article is put together. It's
because we're used to high resolution screens, I think.

**Comment by jread-usgs** [comment]
What journal are you submitting to that has a fig width of 5"?

**Comment by jread-usgs** [comment]
![image](https://cloud.githubusercontent.com/assets/2349007/7326323/151a8d88-ea8a-11e4-8c01-bdc6cc7eabc9.png)

**Comment by jread-usgs** [comment]
you saw this, right? In the existing code:
```R
width = 3.37 # single column width for journal
night_col = 'grey90'
height = 1.9
l_mar = 0.35
b_mar = 0.3
t_mar = 0.05
r_mar= 0.05
gapper = 0.15 # space between panels
ylim = c(0,7.55)
xlim = as.POSIXct(c('2009-07-02 22:00', '2009-07-04 02:00', '2009-07-08 22:00', '2009-07-10 02:00'))


#Create plot and save in user home directory (on Windows, Documents folder, on Mac, Home folder)
png('~/k600_figure.png', res=300, width=width, height=height, units = 'in')
```
3.37" is the default single column width.

**Comment by hdugan** [comment]
Hilary's pointless chiming in: Ugh, figure widths are the worst.
Geophysics: (Standard sizes are 20 picas, or 3.33 inches, for one-column
figures and 26 picas, or 4.33 inches)

**Comment by hdugan** [comment]
Hilary's important chiming in:
Lake.area needs to be in m2, right now it's in hectares. That's why
k600_vachon is flatlined.

**Comment by rBatt** [comment]
@jread no, i only read the fig specs for the old version. Sounds like you
have it figured out (ha). What font size are we using?

5 inches is ~ a 1.5 column, most journals have that, but not all. That's
why I usually do a vertical stacking of my panels as opposed to horizontal,
but I wasn't going to push the point.

@ hillary – is that currently an issue on github?

**Comment by jread-usgs** [comment]
I will take on the change that @hdugan suggested, but am concerned that that issue is in a bunch of examples too?

**Comment by jread-usgs** [comment]
updated. I am happy with this. Can figure out font size at a later time. Should be straightforward:

![image](https://cloud.githubusercontent.com/assets/2349007/7328361/90d32830-ea9a-11e4-9e46-993dde72d487.png)

**Comment by jread-usgs** [comment]
Some notes on this fig: all code is in the package demo, but note that there is a 3 hour running average applied to the *output* of the k functions (not to the input data). If we move forward with this in the ms, it should be clear in the caption. This was necessary in my mind to be able to pull out the differences in the models vs just see a lot of variance. The point is still clear - that these models deal with wind and heatflux in different ways. @lawinslow chose two days in July that have different extremes for wind, low (a) and high (b).

**Comment by jread-usgs** [comment]
closing this. please re-open if edits are needed.
