### ISSUE TITLE
Use `match.arg` for `metab` method arguments?

### ISSUE THREAD

**Issue by jread-usgs** [GLEON/LakeMetabolizer#85]
https://github.com/GLEON/LakeMetabolizer/blob/master/R/metab.R#L136

Seems like this kind of thing is what `match.arg` (base) is for.

**Comment by rBatt** [comment]
You're probably right. I haven't used it much before – feel free to move
that in, or at some point in the distant future I'll do it ;)

Seriously tho, good point
